cache:
  directories:
  - "$HOME/google-cloud-sdk/"
node_js: node
before_install:
- openssl aes-256-cbc -K $encrypted_2dc2bb163caf_key -iv $encrypted_2dc2bb163caf_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash;
  fi
- tar -xzf credentials.tar.gz
- gcloud auth activate-service-account --key-file client-secret.json
script:
- gcloud -q preview app deploy app.yaml --promote
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: omega-zeta
  default: true
  on:
    all_branches: true
install:
- gcloud config set project omega-zeta
