node_js: node
before_install:
- openssl aes-256-cbc -K $encrypted_2dc2bb163caf_key -iv $encrypted_2dc2bb163caf_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash;
  fi
- tar -xzf credentials.tar.gz

deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: omega-zeta
  default: true
  on:
    all_branches: true

